### ISSUE TITLE
View on GitHub link seems to point to another repository

### ISSUE THREAD

**Issue by rosano** [flamedfury/flamedfury.com#2]
I was trying to edit this page https://flamedfury.com/posts/i-love-the-web/ and the link at the bottom seems to point to https://github.com/madrilene/eleventy-excellent/tree/main/src/posts/2021/2021-04-06-web-memories.md

On a quick search, I didn't notice a reference to that in this repo so maybe it's in an environment variable or somewhere external.

**Comment by flamedfury** [comment]
@rosano thanks for pointing this out. I tracked it down to this section in `package.json`

```json
  "keywords": [],
  "repository": {
    "type": "git",
    "url": "https://github.com/flamedfury/flamedfury.git"
  },
  ```

I've updated to my own repo URL and should be good once the site rebuilds :)
